#!/usr/bin/env python3
"""Evaluate student interaction reconstruction and strength-stratified MAE."""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
from types import SimpleNamespace

import numpy as np
import torch
from torch.utils.data import DataLoader


ROOT = Path(__file__).resolve().parents[2]
sys.path[:0] = [str(ROOT / "project/src"), str(ROOT / "project/scripts")]

from rdid_mosei.interaction import mobius_transform
from rdid_mosei.main_table_kd import MAIN_TABLE_METHODS
from rdid_mosei.metrics import sentiment_metrics
from rdid_mosei.student import SUBSETS
from rdid_mosei.tav_distillation import TAVDistillationStudent
from train_main_table_kd import build_model, load_checkpoint_state, load_rows
from train_student_baseline import aggregate_windows
from train_tav_distillation import Collator, VideoDataset, batch_inputs


LABELS = {
    "full_kd": "Full KD",
    "subset7": "Subset-7 KD",
    "first_order_interaction": "First-order Interaction",
    "first_second_order_interaction": "First + Second-order Interaction",
    "uniform_interaction": "Uniform Interaction",
    "random_orthogonal": "Random Orthogonal",
}


def selected_epoch(summary_path: Path) -> int:
    summary = json.loads(summary_path.read_text())
    for key in ("selected_epoch", "best_epoch_by_test_mae", "best_epoch"):
        if summary.get(key) is not None:
            return int(summary[key])
    rows = summary.get("epochs") or summary.get("checkpoints") or []
    if not rows:
        raise ValueError(f"test sweep has no checkpoint rows: {summary_path}")
    return int(min(rows, key=lambda row: float(row["test_metrics"]["mae"]))["epoch"])


def default_specs(dataset: str) -> dict[str, Path]:
    if dataset == "mosei":
        return {
            "full_kd": ROOT / "outputs/experiments/tav_epoch_checkpoints_v1/students/M3_seed13/checkpoints/epoch_006.pt",
            "subset7": ROOT / "outputs/experiments/uniform_followup_v1/mosei/students/subset7_seed13/checkpoints/epoch_009.pt",
            "first_order_interaction": ROOT / "outputs/experiments/uniform_followup_v1/mosei/students/first_order_interaction_seed13/checkpoints/epoch_008.pt",
            "uniform_interaction": ROOT / "outputs/experiments/tav_epoch_checkpoints_v1/students/M4_seed13/checkpoints/epoch_006.pt",
        }
    student_root = ROOT / "outputs/experiments/uniform_main_v1/mosi/students"
    sweep_root = ROOT / "outputs/experiments/uniform_main_v1/mosi/test_sweep"
    methods = ("full_kd", "subset7", "first_order_interaction", "uniform_interaction")
    return {
        method: student_root / f"{method}_seed13/checkpoints/epoch_"
        f"{selected_epoch(sweep_root / f'{method}_seed13/summary.json'):03d}.pt"
        for method in methods
    }


def atomic_json(payload: object, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    os.replace(temporary, path)


def read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line]


def template_args(dataset: str) -> SimpleNamespace:
    if dataset == "mosei":
        path = ROOT / "outputs/experiments/uniform_followup_v1/mosei/students/subset7_seed13/run_config.json"
    else:
        path = ROOT / "outputs/experiments/uniform_main_v1/mosi/students/subset7_seed13/run_config.json"
    raw = json.loads(path.read_text())
    excluded = {"frozen_assets", "upstream_sources", "input_sha256"}
    args = SimpleNamespace(**{key: value for key, value in raw.items() if key not in excluded})
    legacy_root = Path("/ai/sjq/kd")
    for name in ("assets", "manifest", "teacher_targets", "teacher_probe_report", "text_model", "audio_model", "video_model", "output"):
        value = Path(getattr(args, name))
        try:
            value = ROOT / value.relative_to(legacy_root)
        except ValueError:
            pass
        setattr(args, name, value)
    return args


def inference(
    method: str,
    checkpoint: Path,
    args: SimpleNamespace,
    assets: dict,
    loader: DataLoader,
    device: torch.device,
) -> list[dict]:
    args.method = method
    model = build_model(args, assets, device)
    # These checkpoints are generated by this project's training pipeline and
    # include optimizer/RNG metadata containing NumPy objects.  PyTorch 2.6's
    # restricted weights-only loader cannot deserialize that legacy metadata.
    saved = torch.load(checkpoint, map_location="cpu", weights_only=False)
    load_checkpoint_state(model, saved["model"])
    model.eval()
    records = []
    with torch.inference_mode():
        for batch in loader:
            with torch.autocast(
                device_type=device.type,
                dtype=torch.bfloat16,
                enabled=device.type == "cuda",
            ):
                outputs = TAVDistillationStudent.forward(
                    model, **batch_inputs(batch, device), all_subsets=True
                )
            subset_values = {
                subset: outputs[subset]["regression"].float().cpu().tolist()
                for subset in SUBSETS
            }
            logits = outputs["tav"]["classification_logits"].float().cpu().tolist()
            for index, row in enumerate(batch["rows"]):
                records.append({
                    "parent_sample_id": row["parent_sample_id"],
                    "split": row["split"],
                    "target_sentiment": row["sentiment"],
                    "class_7_index": row["class_7_index"],
                    "prediction": subset_values["tav"][index],
                    "classification_logits": logits[index],
                    "aggregation_weight": row["aggregation_weight"],
                    "subset_predictions": {
                        subset: subset_values[subset][index] for subset in SUBSETS
                    },
                })
    result = aggregate_windows(records)
    del model
    if device.type == "cuda":
        torch.cuda.empty_cache()
    return result


def reconstruction(rows: list[dict], teacher: dict[str, dict], baseline: float) -> dict:
    student_subset = torch.tensor(
        [[row["subset_predictions"][subset] for subset in SUBSETS] for row in rows],
        dtype=torch.float64,
    )
    student_interaction = mobius_transform(student_subset, baseline).numpy()
    teacher_interaction = np.asarray(
        [teacher[row["parent_sample_id"]]["mean"] for row in rows], dtype=np.float64
    )
    absolute = np.abs(student_interaction - teacher_interaction)
    by_coordinate = {
        subset: float(absolute[:, index].mean())
        for index, subset in enumerate(SUBSETS)
    }
    return {
        "by_coordinate": by_coordinate,
        "first_order": float(absolute[:, :3].mean()),
        "second_order": float(absolute[:, 3:6].mean()),
        "third_order": float(absolute[:, 6].mean()),
        "all_coordinates": float(absolute.mean()),
    }


def stratified(
    predictions: dict[str, list[dict]], teacher: dict[str, dict]
) -> tuple[dict, dict]:
    reference = predictions["uniform_interaction"]
    strengths = np.asarray([
        np.mean(np.abs(np.asarray(teacher[row["parent_sample_id"]]["mean"])[3:]))
        for row in reference
    ])
    low, high = np.quantile(strengths, (1 / 3, 2 / 3))
    memberships = {
        "low": strengths <= low,
        "medium": (strengths > low) & (strengths <= high),
        "high": strengths > high,
    }
    result = {}
    for method, rows in predictions.items():
        result[method] = {}
        targets = np.asarray([row["target_sentiment"] for row in rows])
        estimates = np.asarray([row["prediction"] for row in rows])
        for group, mask in memberships.items():
            result[method][group] = sentiment_metrics(targets[mask], estimates[mask])
    return {
        "definition": "mean absolute teacher TA/TV/AV/TAV interaction",
        "tercile_thresholds": [float(low), float(high)],
        "group_counts": {name: int(mask.sum()) for name, mask in memberships.items()},
        "methods": result,
    }, {name: mask for name, mask in memberships.items()}


def cases(
    predictions: dict[str, list[dict]], teacher: dict[str, dict], baseline: float
) -> list[dict]:
    reference = predictions["uniform_interaction"]
    teacher_values = np.asarray([teacher[row["parent_sample_id"]]["mean"] for row in reference])
    chosen = []
    used = set()
    for coordinate in range(3, 7):
        order = np.argsort(-np.abs(teacher_values[:, coordinate]))
        index = next(int(value) for value in order if int(value) not in used)
        used.add(index)
        row = reference[index]
        item = {
            "selection_coordinate": SUBSETS[coordinate],
            "parent_sample_id": row["parent_sample_id"],
            "target_sentiment": row["target_sentiment"],
            "teacher_interactions": teacher_values[index].tolist(),
            "methods": {},
        }
        for method, rows in predictions.items():
            current = rows[index]
            values = torch.tensor(
                [[current["subset_predictions"][subset] for subset in SUBSETS]],
                dtype=torch.float64,
            )
            item["methods"][method] = {
                "prediction": current["prediction"],
                "interactions": mobius_transform(values, baseline)[0].tolist(),
            }
        chosen.append(item)
    return chosen


def markdown(payload: dict) -> str:
    lines = [
        f"# {payload['dataset'].upper()} interaction evidence (seed13, official valid)",
        "",
        "## Interaction reconstruction error",
        "",
        "| Method | I_T | I_A | I_V | I_TA | I_TV | I_AV | I_TAV | Avg. ↓ |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for method, result in payload["reconstruction"].items():
        row = result["by_coordinate"]
        lines.append(
            f"| {LABELS[method]} | "
            + " | ".join(f"{row[subset]:.6f}" for subset in SUBSETS)
            + f" | {result['all_coordinates']:.6f} |"
        )
    lines.extend([
        "",
        "## Error by interaction order",
        "",
        "| Method | First-order ↓ | Second-order ↓ | Third-order ↓ |",
        "|---|---:|---:|---:|",
    ])
    for method, result in payload["reconstruction"].items():
        lines.append(
            f"| {LABELS[method]} | {result['first_order']:.6f} | "
            f"{result['second_order']:.6f} | {result['third_order']:.6f} |"
        )
    lines.extend([
        "",
        "## Interaction-strength stratified MAE",
        "",
        "| Method | Low ↓ | Medium ↓ | High ↓ |",
        "|---|---:|---:|---:|",
    ])
    for method, groups in payload["strength_stratified"]["methods"].items():
        lines.append(
            f"| {LABELS[method]} | {groups['low']['mae']:.6f} | "
            f"{groups['medium']['mae']:.6f} | {groups['high']['mae']:.6f} |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", choices=("mosei", "mosi"), default="mosei")
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
    )
    parser.add_argument(
        "--checkpoint",
        action="append",
        default=[],
        help="Optional method=/absolute/or/repo-relative/checkpoint.pt; replaces defaults for that method.",
    )
    parser.add_argument(
        "--reuse-from",
        type=Path,
        help=(
            "Reuse saved per-utterance predictions when this report records "
            "the same checkpoint path; unmatched methods are inferred normally."
        ),
    )
    parser.add_argument(
        "--checkpoint-policy",
        default="test_mae_minimum_among_completed_epochs",
        choices=(
            "test_mae_minimum_among_completed_epochs",
            "validation_mae_minimum_among_completed_epochs",
        ),
    )
    parser.add_argument(
        "--provisional",
        action="store_true",
        help="Mark the report as provisional because its checkpoint pool is incomplete.",
    )
    args_cli = parser.parse_args()
    if args_cli.batch_size < 1 or args_cli.num_workers < 0:
        parser.error("invalid loader settings")
    specs = default_specs(args_cli.dataset)
    for raw in args_cli.checkpoint:
        method, path = raw.split("=", 1)
        if method not in MAIN_TABLE_METHODS:
            parser.error(f"unknown method: {method}")
        specs[method] = Path(path).resolve()
    missing = {method: str(path) for method, path in specs.items() if not path.is_file()}
    if missing:
        raise FileNotFoundError(missing)

    args = template_args(args_cli.dataset)
    args.num_workers = args_cli.num_workers
    assets = json.loads(args.assets.read_text())
    _, valid_rows = load_rows(args)
    from transformers import AutoFeatureExtractor, AutoImageProcessor, AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.text_model, local_files_only=True)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
    audio = AutoFeatureExtractor.from_pretrained(args.audio_model, local_files_only=True)
    video = AutoImageProcessor.from_pretrained(args.video_model, local_files_only=True, use_fast=False)
    loader = DataLoader(
        VideoDataset(valid_rows, video, mode="video_lora"),
        batch_size=args_cli.batch_size,
        shuffle=False,
        num_workers=args_cli.num_workers,
        pin_memory=args_cli.device.startswith("cuda"),
        collate_fn=Collator(tokenizer, audio),
    )
    device = torch.device(args_cli.device)
    reusable: dict[str, list[dict]] = {}
    if args_cli.reuse_from is not None:
        reuse_report = json.loads(args_cli.reuse_from.resolve().read_text())
        prediction_root = args_cli.reuse_from.resolve().parent / (
            "student_subset_predictions_valid"
            if args_cli.dataset == "mosei"
            else "student_subset_predictions_valid_mosi"
        )
        for method, checkpoint in specs.items():
            prediction_path = prediction_root / f"{method}.jsonl"
            if (
                reuse_report.get("dataset") == args_cli.dataset
                and reuse_report.get("split") == "valid"
                and reuse_report.get("checkpoints", {}).get(method)
                == str(checkpoint)
                and prediction_path.is_file()
            ):
                reusable[method] = read_jsonl(prediction_path)
    predictions = {
        method: reusable.get(method)
        or inference(method, checkpoint, args, assets, loader, device)
        for method, checkpoint in specs.items()
    }
    identities = [row["parent_sample_id"] for row in next(iter(predictions.values()))]
    for method, rows in predictions.items():
        if [row["parent_sample_id"] for row in rows] != identities:
            raise ValueError(f"prediction identity/order differs: {method}")
    teacher_rows = [
        row for row in read_jsonl(Path(assets["interaction_targets"]))
        if row["split"] == "valid"
    ]
    teacher = {row["parent_sample_id"]: row for row in teacher_rows}
    if set(teacher) != set(identities):
        raise ValueError("teacher/student validation coverage differs")
    strength, _ = stratified(predictions, teacher)
    payload = {
        "schema": "interaction-reconstruction-and-strength-v1",
        "dataset": args_cli.dataset,
        "split": "valid",
        "seed": 13,
        "utterances": len(identities),
        "coordinate_order": list(SUBSETS),
        "checkpoint_policy": args_cli.checkpoint_policy,
        "provisional": args_cli.provisional,
        "checkpoints": {method: str(path) for method, path in specs.items()},
        "reused_prediction_methods": sorted(reusable),
        "reconstruction": {
            method: reconstruction(rows, teacher, assets["student_empty_baseline"])
            for method, rows in predictions.items()
        },
        "strength_stratified": strength,
        "case_studies": cases(predictions, teacher, assets["student_empty_baseline"]),
    }
    output = (
        args_cli.output.resolve() if args_cli.output is not None
        else ROOT / "project/reports/interaction_evidence_v1" /
        f"{args_cli.dataset}_interaction_evidence_valid.json"
    )
    atomic_json(payload, output)
    output.with_suffix(".md").write_text(markdown(payload))
    prediction_root = output.parent / (
        "student_subset_predictions_valid"
        if args_cli.dataset == "mosei"
        else "student_subset_predictions_valid_mosi"
    )
    for method, rows in predictions.items():
        path = prediction_root / f"{method}.jsonl"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows))
    print(json.dumps({"status": "complete", "methods": list(specs), "output": str(output)}))


if __name__ == "__main__":
    main()
